
I2V    = bash ../../../etc/convert-i2v.bash
OPT    = 4 1
EFFECT = fade

all:
	$(I2V) $(OPT) placeholder-black-1.png placeholder-black-2.png placeholder-black-loop.smp4  $(EFFECT)
	$(I2V) $(OPT) placeholder-white-1.png placeholder-white-2.png placeholder-white-loop.smp4  $(EFFECT)

