
I2V = bash ../../../etc/convert-i2v.bash
OPT = 4 1

all:
	$(I2V) $(OPT) placeholder-black-1.png placeholder-black-2.png placeholder-black-loop.webm  slideleft
	$(I2V) $(OPT) placeholder-black-1.png placeholder-black-2.png placeholder-black-loop.swebm slideleft
	$(I2V) $(OPT) placeholder-black-1.png placeholder-black-2.png placeholder-black-loop.smp4  slideleft
	$(I2V) $(OPT) placeholder-white-1.png placeholder-white-2.png placeholder-white-loop.webm  slideleft
	$(I2V) $(OPT) placeholder-white-1.png placeholder-white-2.png placeholder-white-loop.swebm slideleft
	$(I2V) $(OPT) placeholder-white-1.png placeholder-white-2.png placeholder-white-loop.smp4  slideleft

